ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_homework` VALUES IN  (("$[yyyyMM-1]","homework"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_course_schedule` VALUES IN  (("$[yyyyMM-1]","course-schedule"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_afterclass` VALUES IN  (("$[yyyyMM-1]","afterclass"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_habit` VALUES IN  (("$[yyyyMM-1]","habit"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_vote` VALUES IN  (("$[yyyyMM-1]","vote"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_score` VALUES IN  (("$[yyyyMM-1]","score"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_assessment` VALUES IN  (("$[yyyyMM-1]","assessment"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_notice` VALUES IN  (("$[yyyyMM-1]","notice"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d ADD PARTITION IF NOT EXISTS `p$[yyyyMM-1]_questionnaire` VALUES IN  (("$[yyyyMM-1]","questionnaire"))

ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_homework` VALUES IN  (("$[yyyyMM-1]","homework"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_course_schedule` VALUES IN  (("$[yyyyMM-1]","course-schedule"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_afterclass` VALUES IN  (("$[yyyyMM-1]","afterclass"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_habit` VALUES IN  (("$[yyyyMM-1]","habit"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_vote` VALUES IN  (("$[yyyyMM-1]","vote"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_score` VALUES IN  (("$[yyyyMM-1]","score"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_assessment` VALUES IN  (("$[yyyyMM-1]","assessment"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_notice` VALUES IN  (("$[yyyyMM-1]","notice"))
ALTER TABLE ads__school_activity__activity_user_stat_history__d drop  PARTITION  if EXISTS `p$[yyyyMM-1]_questionnaire` VALUES IN  (("$[yyyyMM-1]","questionnaire"))