DROP TABLE IF EXISTS dim__whole_school;
CREATE TABLE IF NOT EXISTS dim__whole_school
(
    `school_id`                   BIGINT(20) COMMENT '学校标识',
    `stat_time`                   STRING COMMENT '数据生成时间',
    `created_by`                  BIGINT(20) COMMENT '活动创建者',
    `created_time`                STRING COMMENT '创建时间',
    `created_date`                STRING COMMENT '创建日期',
    `last_modified_by`            BIGINT(20) COMMENT '活动最后更新者',
    `last_modified_time`          STRING COMMENT '最后更新时间',
    `last_modified_date`          STRING COMMENT '最后更新日期',
    `school_name`                 STRING COMMENT '学校名',
    `school_section`              STRING COMMENT '学校学段',
    `school_educational_system`   STRING COMMENT '学校学制',
    `school_brief_introduction`   STRING COMMENT '学校简介',
    `school_motto`                STRING COMMENT '校训',
    `school_master_ids`           STRING COMMENT '校长标识（数组）',
    `school_master_name`          STRING COMMENT '学校校长',
    `school_standards`            STRING COMMENT '达标类型（学校等级）',
    `school_type`                 STRING COMMENT '学校性质（学校办别）',
    `school_nature`               STRING COMMENT '学校性质',
    `school_area_code`            STRING COMMENT '行政区划码',
    `school_zip_code`             STRING COMMENT '学校邮编',
    `school_org_code`             STRING COMMENT '组织编码',
    `school_number`               STRING COMMENT '学校编码',
    `school_inst_code`            STRING COMMENT '学校机构代码',
    `school_edu_type`             STRING COMMENT '学校教育类型',
    `school_address`              STRING COMMENT '地址',
    `school_location`             STRING COMMENT '位置',
    `school_phone`                STRING COMMENT '电话',
    `school_contact`              STRING COMMENT '联系人',
    `school_email`                STRING COMMENT '电子邮箱',
    `school_icon`                 STRING COMMENT '图标',
    `school_label`                STRING COMMENT '个性化标签',
    `school_code`                 STRING COMMENT '学校短码',
    `website`                     STRING COMMENT '学校网站',
    `school_edu_type_code`        STRING COMMENT '学校办学类型码',
    `school_fund_type_code`       STRING COMMENT '学校办别码',
    `school_urban_and_rural_type` STRING COMMENT '学校所在地城乡类型',
    `source_type`                 STRING COMMENT '来源类型',
    `org_id`                      BIGINT(20) COMMENT 'UC组织标识',
    `grade_root_id`               BIGINT(20) COMMENT '年级根节点',
    `dept_root_id`                BIGINT(20) COMMENT '部门根节点',
    `tenant_id`                   BIGINT(20) COMMENT '租户标识',
    `version`                     BIGINT(20) COMMENT '版本号',
    `is_other_name`               INT(11) COMMENT '是否是其他名称',
    `node_path`                   STRING COMMENT '节点路径',
    `inst_id`                     BIGINT(20) COMMENT '机构标识',
    `area_id`                     BIGINT(20) COMMENT '所属区域标识',
    `area_name`                   STRING COMMENT '所属区域名称',
    `area_code`                   STRING COMMENT '所属区域编码',
    `area_short_name`             STRING COMMENT '所属区域短名称',
    `area_merger_name`            STRING COMMENT '所属区域合并名称',
    `area_merger_short_name`      STRING COMMENT '所属区域合并短名称',
    `area_level`                  INT(11) COMMENT '所属区域层级',
    `province_id`                 BIGINT(20) COMMENT '区域省标识',
    `province_name`               STRING COMMENT '区域省名称',
    `province_code`               STRING COMMENT '区域省编码',
    `province_short_name`         STRING COMMENT '区域省短名称',
    `city_id`                     BIGINT(20) COMMENT '区域市标识',
    `city_name`                   STRING COMMENT '区域市名称',
    `city_code`                   STRING COMMENT '区域市编码',
    `city_short_name`             STRING COMMENT '区域市短名称',
    `county_id`                   BIGINT(20) COMMENT '区域区县标识',
    `county_name`                 STRING COMMENT '区域区县名称',
    `county_code`                 STRING COMMENT '区域区县编码',
    `county_short_name`           STRING COMMENT '区域区县短名称',
    `region_code`                 STRING COMMENT '所属大区编码',
    `region_name`                 STRING COMMENT '所属大区名称',
    `area_tag`                    STRING COMMENT '地区标签：NORMAL=中小学常规业务行政区划, SAR=港澳台, SUNSHINE=阳光学校区, NCET=央馆省（测试区）',
    index idx_province_id_key(province_id) USING bitmap COMMENT '区域省标识索引',
    index idx_city_id_key(city_id) USING bitmap COMMENT '区域市标识索引',
    index idx_county_id_key(county_id) USING bitmap COMMENT '区域区县标识索引',
    index idx_area_tag_key(area_tag) USING bitmap COMMENT '地区标签索引',
    index idx_school_section_key(school_section) USING bitmap COMMENT '学校学段索引',
    index idx_area_id_key(area_id) USING bitmap COMMENT '所属区域标识索引'
) ENGINE=OLAP
    UNIQUE  KEY(school_id)
    COMMENT '基础数据域-学校维表-每天-全量'
        DISTRIBUTED BY HASH(school_id) BUCKETS 4
        PROPERTIES (
        "replication_allocation" = "tag.location.default: 3",
        "in_memory" = "false",
        "storage_format" = "V2"
        );
SELECT school_id,stat_time,created_by,created_time,created_date,last_modified_by,last_modified_time,last_modified_date,school_name,school_section,school_educational_system,school_brief_introduction,school_motto,school_master_ids,school_master_name,school_standards,school_type,school_nature,school_area_code,school_zip_code,school_org_code,school_number,school_inst_code,school_edu_type,school_address,school_location,school_phone,school_contact,school_email,school_icon,school_label,school_code,website,school_edu_type_code,school_fund_type_code,school_urban_and_rural_type,source_type,org_id,grade_root_id,dept_root_id,tenant_id,version,is_other_name,node_path,inst_id,area_id,area_name,area_code,area_short_name,area_merger_name,area_merger_short_name,area_level,province_id,province_name,province_code,province_short_name,city_id,city_name,city_code,city_short_name,county_id,county_name,county_code,county_short_name,region_code,region_name,area_tag
FROM dim__whole_school