DROP TABLE  IF EXISTS nddc.dws__tala__area_teaching_research__participate_stat__da__full_bak20241213;
ALTER table nddc.dws__tala__area_teaching_research__participate_stat__da__full RENAME to dws__tala__area_teaching_research__participate_stat__da__full_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.dws__tala__area_teaching_research__participate_stat__da__full like nddc_uat.dws__tala__area_teaching_research__participate_stat__da__full;
INSERT OVERWRITE  TABLE nddc.dws__tala__area_teaching_research__participate_stat__da__full PARTITION (pc,ptc,activity_type)
select * from nddc_uat.dws__tala__area_teaching_research__participate_stat__da__full;

DROP TABLE  IF EXISTS nddc.dws__tala__area_teaching_research__participate_stat__dd__full_bak20241213;
ALTER table nddc.dws__tala__area_teaching_research__participate_stat__dd__full RENAME to dws__tala__area_teaching_research__participate_stat__dd__full_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.dws__tala__area_teaching_research__participate_stat__dd__full like nddc_uat.dws__tala__area_teaching_research__participate_stat__dd__full;
INSERT OVERWRITE  TABLE nddc.dws__tala__area_teaching_research__participate_stat__dd__full PARTITION (dt,activity_type)
select * from nddc_uat.dws__tala__area_teaching_research__participate_stat__dd__full;

DROP TABLE  IF EXISTS nddc.dws__tala__area_teaching_research__publish_stat__da__full__full_bak20241213;
ALTER table nddc.dws__tala__area_teaching_research__publish_stat__da__full RENAME to dws__tala__area_teaching_research__publish_stat__da__full__full_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.dws__tala__area_teaching_research__publish_stat__da__full like nddc_uat.dws__tala__area_teaching_research__publish_stat__da__full;
INSERT OVERWRITE  TABLE nddc.dws__tala__area_teaching_research__publish_stat__da__full PARTITION (pc,ptc,activity_type)
select * from nddc_uat.dws__tala__area_teaching_research__publish_stat__da__full;

DROP TABLE  IF EXISTS nddc.dws__tala__area_teaching_research__publish_stat__dd__full_bak20241213;
ALTER table nddc.dws__tala__area_teaching_research__publish_stat__dd__full RENAME to dws__tala__area_teaching_research__publish_stat__dd__full_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.dws__tala__area_teaching_research__publish_stat__dd__full like nddc_uat.dws__tala__area_teaching_research__publish_stat__dd__full;
INSERT OVERWRITE  TABLE nddc.dws__tala__area_teaching_research__publish_stat__dd__full PARTITION (dt,activity_type)
select * from nddc_uat.dws__tala__area_teaching_research__publish_stat__dd__full;

DROP TABLE  IF EXISTS nddc.ads__region_app__teaching_research__activity_overview_stat_d_bak20241213;
ALTER table nddc.ads__region_app__teaching_research__activity_overview_stat_d RENAME to ads__region_app__teaching_research__activity_overview_stat_d_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.ads__region_app__teaching_research__activity_overview_stat_d like nddc_uat.ads__region_app__teaching_research__activity_overview_stat_d;
INSERT OVERWRITE  TABLE nddc.ads__region_app__teaching_research__activity_overview_stat_d PARTITION (pc,ptc,activity_type)
select * from nddc_uat.ads__region_app__teaching_research__activity_overview_stat_d;

DROP TABLE  IF EXISTS nddc.ads__region_app__teaching_research__activity_trend_stat_d_bak20241213;
ALTER table nddc.ads__region_app__teaching_research__activity_trend_stat_d RENAME to ads__region_app__teaching_research__activity_trend_stat_d_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.ads__region_app__teaching_research__activity_trend_stat_d like nddc_uat.ads__region_app__teaching_research__activity_trend_stat_d;
INSERT OVERWRITE  TABLE nddc.ads__region_app__teaching_research__activity_trend_stat_d PARTITION (dt,activity_type)
select * from nddc_uat.ads__region_app__teaching_research__activity_trend_stat_d;

DROP TABLE  IF EXISTS nddc.ads__region_app__teaching_research__group_overview_stat_d_bak20241213;
ALTER table nddc.ads__region_app__teaching_research__group_overview_stat_d RENAME to ads__region_app__teaching_research__group_overview_stat_d_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.ads__region_app__teaching_research__group_overview_stat_d like nddc_uat.ads__region_app__teaching_research__group_overview_stat_d;
INSERT OVERWRITE  TABLE nddc.ads__region_app__teaching_research__group_overview_stat_d PARTITION (pc,ptc)
select * from nddc_uat.ads__region_app__teaching_research__group_overview_stat_d;

DROP TABLE  IF EXISTS nddc.ads__region_app__teaching_research__group_trend_stat_d_bak20241213;
ALTER table nddc.ads__region_app__teaching_research__group_trend_stat_d RENAME to ads__region_app__teaching_research__group_trend_stat_d_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.ads__region_app__teaching_research__group_trend_stat_d like nddc_uat.ads__region_app__teaching_research__group_trend_stat_d;
INSERT OVERWRITE  TABLE nddc.ads__region_app__teaching_research__group_trend_stat_d PARTITION (dt)
select * from nddc_uat.ads__region_app__teaching_research__group_trend_stat_d;

DROP TABLE  IF EXISTS nddc.ads__school_teaching_research__activity_user_stat__d_bak20241213;
ALTER table nddc.ads__school_teaching_research__activity_user_stat__d RENAME to ads__school_teaching_research__activity_user_stat__d_bak20241213;
CREATE TABLE IF NOT EXISTS nddc.ads__school_teaching_research__activity_user_stat__d like nddc_uat.ads__school_teaching_research__activity_user_stat__d;
INSERT OVERWRITE  TABLE nddc.ads__school_teaching_research__activity_user_stat__d PARTITION (dt,activity_type)
select * from nddc_uat.ads__school_teaching_research__activity_user_stat__d;